/*map dimensions*/
#define MAX_DIST 120.0f
#define ARRIVAL_DIST (MAX_DIST*10)
#define DIAGONAL_MAP 1247.076f
/*player*/
#define SPACECRAFT_SPEED 20.0f
#define SPACECRAFT_SPEED_MAX 50.0f
#define VELOCITY_SIDE 8.0f
#define VELOCITY_FORWARD VELOCITY_SIDE
#define LIMIT_VELOCITY 200.0f
/*shots*/
#define BULLET_SPEED_PER_SECOND 200.0f
#define FIRING_RATE_PER_SECOND 3.0f
/*enemies*/
#define INITIAL_ENEMY_DIST 10000.0f
#define DISTANCE_FROM_PLAYER 150.0f
#define ENEMY_BULLET_SPEED_PER_SECOND .2f
#define VELOCITY_ENEMY 70.0f
#define ENEMY_BULLET_SIZE 4.0f
